version: "3.9"

services:
  flask-app:
    image: ${DOCKERHUB_REPO}/flask-app:latest
    container_name: flask-app
    restart: unless-stopped
    depends_on:
      - flask-app-database
    environment:
      _SECRET_KEY: ${_SECRET_KEY}
      _ADMIN_PASS: ${_ADMIN_PASS}
      _DB_PROVIDER: postgresql
      _DB_HOST: flask-app-database
      _DB_DATABASE: flask-app
      _DB_PASS: ${_DB_PASS}
      HOST: 0.0.0.0
      PORT: 8080
      WORKERS: 4
      THREADS: 64
      WORKER_CONNECTIONS: 8192
      TZ: America/Sao_Paulo
    networks:
      default:
        aliases:
          - flask-app
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
  flask-app-database:
    image: postgres:latest
    container_name: flask-app-database
    restart: unless-stopped
    environment:
      POSTGRES_DB: flask-app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${_DB_PASS}
      TZ: America/Sao_Paulo
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin" ]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql
    networks:
      default:
        aliases:
          - flask-app-database