name: Test and Build

on:
  push:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.version.outputs.VERSION }}
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3

    -
      name: Setting version
      id: version
      run: |
        echo "VERSION=v$(cat ./src/app/version.yaml | tr -d '[:space:]' | awk -F: '{print $2}')" | tee -a $GITHUB_ENV $GITHUB_OUTPUT

    -
      name: Checking version.yaml
      run: |
        CHECK=$(curl -s -H 'Authorization: Bearer ${{ secrets.DOCKERHUB_TOKEN }}' 'https://hub.docker.com/v2/namespaces/${{ secrets.DOCKERHUB_USER }}/repositories/flask-app/tags/${{ env.VERSION }}'  | jq '.tag_status')
        bash ./src/check_version.sh $CHECK

    -
      name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    -
      name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r src/requirements.txt

    -
      name: Run unittests
      run: |
        export _TESTING=1
        python3 -m pytest src/tests/unittests

  docker_hub:
    name: Publish docker image to docker hub
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/master'
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      -
        name: Extract metadata for docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USER }}/flask-app

      -
        name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:src"
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/flask-app:${{ needs.tests.outputs.VERSION }} , ${{ secrets.DOCKERHUB_USER }}/flask-app:latest
          labels: ${{ steps.meta.outputs.labels }}
